### ISSUE TITLE
Missing AridOpti.obj

### ISSUE THREAD

**Issue by patrickmeehan** [korgan00/TFG-Atmospheric-Scattering#1]
Thanks for sharing this! I was able to build and run after comment out codepaths requiring AridOpti.obj. Also wasn't able to run with "majestic mountain.obj" or "Mountain Valley.obj". If you have time to add those, would love to run the full demo.

**Comment by korgan00** [comment]
Sorry mate, i read this today!

That ".obj" have rights and i wasnt able to upload them. You can find many free obj files in the web, however the city is a good example.
